---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: http-mapping-search-index-server
      prefix: /code-search/
      rewrite: /
      method: GET
      service: search-index-server.kubeflow:8008
  labels:
    app: search-index-server
    ksonnet.io/component: search-index-server
  name: search-index-server
  namespace: kubeflow
spec:
  ports:
  - name: nmslib-serve-http
    port: 8008
    targetPort: 8008
  selector:
    app: search-index-server
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: search-index-server
    ksonnet.io/component: search-index-server
  name: search-index-server
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-index-server
  template:
    metadata:
      labels:
        app: search-index-server
    spec:
      containers:
      - command:
        - python
        - -m
        - code_search.nmslib.cli.start_search_server
        - --problem={{T2T_PROBLEM}}
        - --data_dir={{DATA_DIR}}
        - --lookup_file={{LOOKUP_FILE}}
        - --index_file={{INDEX_FILE}}
        - --serving_url=http://query-embed-server.kubeflow:8500/v1/models/t2t-code-search:predict
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/user-gcp-sa.json
        image: gcr.io/kubeflow-examples/code-search-ui:v20181122-dc0e646-dirty-043a63
        name: search-index-server
        ports:
        - containerPort: 8008
        volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials
      volumes:
      - name: gcp-credentials
        secret:
          secretName: user-gcp-sa
