---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: create-search-index
  name: create-search-index-{{EXPERIMENT}}
  namespace: kubeflow
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: create-search-index-{{EXPERIMENT}}
    spec:
      containers:
      - command:
        - python
        - -m
        - code_search.nmslib.cli.create_search_index
        - --data_dir={{EMBEDDING_DIR}}
        - --lookup_file={{LOOKUP_FILE}}
        - --index_file={{INDEX_FILE}}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/user-gcp-sa.json
        image: {{IMAGE_DATAFLOW}}
        name: dataflow
        resources:
          limits:
            memory: 30Gi
          requests:
            memory: 16Gi
        volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials
        workingDir: /src
      restartPolicy: Never
      volumes:
      - name: gcp-credentials
        secret:
          secretName: user-gcp-sa
