apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: t2t-code-search-trainer
  name: t2t-code-search-trainer-{{EXPERIMENT}}
  namespace: kubeflow
spec:
      template:
        spec:
          containers:
          - command:
            - t2t-trainer
            - --problem={{T2T_PROBLEM}}
            - --model={{T2T_MODEL}}
            - --hparams_set={{HPARAMS_SET}}
            - --data_dir={{DATA_DIR}}
            - --output_dir={{WORKING_DIR}}/output
            - --train_steps={{TRAIN_STEPS}}
            - --eval_steps={{EVAL_STEPS}}
            - --t2t_usr_dir=/app/code_search/t2t
            - --schedule=train
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/gcp-credentials/user-gcp-sa.json
            image: {{IMAGE_T2T}}
            name: tensorflow
            volumeMounts:
            - mountPath: /secret/gcp-credentials
              name: gcp-credentials
          restartPolicy: OnFailure
          volumes:
          - name: gcp-credentials
            secret:
              secretName: user-gcp-sa
