apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: t2t-code-search-datagen
  name: t2t-code-search-datagen-{{EXPERIMENT}}
  namespace: kubeflow
spec:
  template:
    metadata:
      labels:
        app: t2t-code-search-datagen
    spec:
      containers:
      - command:
        - t2t-datagen
        - --t2t_usr_dir=/app/code_search/t2t
        - --problem={{T2T_PROBLEM}}
        - --data_dir={{DATA_DIR}}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/user-gcp-sa.json
        image: gcr.io/kubeflow-examples/code-search@sha256:c9d879bcdcbc176721d95c1c0e0b00034cdbeb800b4733a9d5f3cb853f406559
        name: t2t-datagen
        volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials
        workingDir: /src
      restartPolicy: OnFailure
      volumes:
      - name: gcp-credentials
        secret:
          secretName: user-gcp-sa
